### ISSUE TITLE
Classloader failed to find class of XXX

### ISSUE THREAD

**Issue by kris-w-dev** [qcdong2016/creator-native-bridge#1]
JS:        
native.callClass("NativeTest", "test", "Hello Native", 123, true, (str, number, bool) => {
            console.log(str, number, bool)
            that.label.string = str;
})

JAVA:
package org.cocos2dx.javascript;
class NativeTest {
    static public void test(String s, float d, boolean b, String cbName) {
        System.out.print("NativeTest test:" + s);
        Js.call(cbName, "Hello Js", 321, false);
    }
}

JS: clazz: NativeTest
JS: method: test
JS: methodSignature: (Ljava/lang/String;FZLjava/lang/String;)V
JS: parameters: Hello Native 123 true 1

检查了路径个参数都对，不知为何Classloader failed to find class of：

D/JniHelper: JniHelper::getJavaVM(), pthread_self() = -1053613600
D/JavaScriptJavaBridge: Classloader failed to find class of org/cocos2dx/javascript/NativeTest
E/JavaScriptJavaBridge: [ERROR] (/Applications/CocosCreator/Creator/2.4.4/CocosCreator.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/JavaScriptJavaBridge.cpp, 605): call valid: 0, call.getArgumentsCount()= 4
E/JavaScriptJavaBridge: [ERROR] Failed to invoke JavaScriptJavaBridge_callStaticMethod, location: /Applications/CocosCreator/Creator/2.4.4/CocosCreator.app/Contents/Resources/cocos2d-x/cocos/scripting/js-bindings/manual/JavaScriptJavaBridge.cpp:611

**Comment by qcdong2016** [comment]
嗯。上次发现这个问题了，忘了同步到仓库。你再试试新的

**Comment by kris-w-dev** [comment]
感谢你的回复，我尝试了新的提交，但在我的项目中问题依然存在，相比较您提供的demo， 我只改动了 static defaultPackage = "org/cocos2dx/javascript/"，因为我的版本package是org.cocos2dx.javascript 。

**Comment by kris-w-dev** [comment]
D/JavaScriptJavaBridge: Classloader failed to find class of org/cocos2dx/javascript/NativeTest

**Comment by qcdong2016** [comment]
那你自己找找问题吧。这个应该比较简单
